/**
 * The content-only rule, defined once.
 *
 * A pull request is content-only when every file it changes is entry content:
 * a file inside an entry's folder, `<entry.path>/<slug>/` (default
 * `catalog/<slug>/`), whose type a submission can produce, or `_data/derivatives.json`, which the
 * submission and thumbnail workflows rewrite alongside the images. Such a pull
 * request runs only the content check (`validate.yml`'s `content` job); every
 * other check workflow gates its jobs on this answer through
 * `.github/workflows/content-only.yml`.
 *
 * Fails toward running everything: no files, an unsafe `entry.path`, or any
 * other file at all means "not content-only".
 *
 * Pure: no filesystem, no git. See scripts/content_only.mjs for the CLI and
 * test/scripts/content_only.test.mjs.
 */

/** Generated by scripts/derive_images.mjs and committed by the submission bots. */
const CONTENT_FILES = ['_data/derivatives.json'];

/**
 * What the scaffolders write inside an entry folder: index.md, screenshots and
 * their AVIF/WebP derivatives, PDF decks and their thumbnails. Script, markup
 * and data files are left out on purpose; they would skip ESLint and CodeQL.
 */
const CONTENT_EXTENSIONS = new Set(['.md', '.pdf', '.png', '.jpg', '.jpeg', '.gif', '.webp', '.avif']);

/** One or more plain folder names: no dot- or underscore-led segments, no `..`. */
const SAFE_FOLDER = /^[A-Za-z0-9][A-Za-z0-9-]*(?:\/[A-Za-z0-9][A-Za-z0-9-]*)*$/u;

/**
 * The paths that count as entry content for a schema.
 * @param {object|null} schema a parsed _data/schema.yml
 * @returns {{folders: string[], files: string[]}} folders end in `/`
 */
export function contentPaths(schema) {
  const configured = schema?.entry?.path;
  const raw = typeof configured === 'string' && configured.trim() !== '' ? configured.trim() : 'catalog';
  const folder = raw.replace(/^\/+|\/+$/gu, '');
  // An entry.path of "." or ".github" would make the whole repository, or the
  // workflows, look like content. Treat it as "nothing is content" instead.
  if (!SAFE_FOLDER.test(folder)) return { folders: [], files: [] };
  return { folders: [`${folder}/`], files: CONTENT_FILES };
}

/**
 * @param {string} file a repository-relative path
 * @param {{folders: string[], files: string[]}} paths from contentPaths()
 */
function isContentFile(file, paths) {
  if (paths.files.includes(file)) return true;
  const extension = (/\.[^./]+$/u.exec(file)?.[0] ?? '').toLowerCase();
  // Inside an entry's own folder (<entry.path>/<slug>/...), not beside the entries.
  const inEntry = paths.folders.some(
    (folder) => file.startsWith(folder) && file.slice(folder.length).includes('/')
  );
  return inEntry && CONTENT_EXTENSIONS.has(extension);
}

/**
 * Is every changed file entry content?
 * @param {string[]|undefined} files the pull request's changed paths
 * @param {object|null} schema a parsed _data/schema.yml
 * @returns {boolean} false for an empty list
 */
export function isContentOnly(files, schema) {
  const paths = contentPaths(schema);
  if (!Array.isArray(files) || files.length === 0 || paths.folders.length === 0) return false;
  return files.every((file) => typeof file === 'string' && file !== '' && isContentFile(file, paths));
}
