#!/usr/bin/env node
/**
 * Regenerates `_includes/icon.html` from Heroicons (MIT, 24px outline set).
 *
 * The include exposes a stable, semantic icon vocabulary (`shield`, `rocket`,
 * `lock`…) that `_data/schema.yml` `icon:` and `option_meta.icon` refer to, and
 * maps each name to a Heroicons file. Add a name here, run `node scripts/build_icons.mjs`, update
 * the `_includes/icon.html` digest in `quality/vendored-assets.json`, review the diff and notices,
 * then run `npm run licenses:check`. Icons render inline as `<svg aria-hidden="true">`; callers
 * add visible or sr-only text.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const HERO = join(root, 'node_modules', 'heroicons', '24', 'outline');

/** Semantic name -> Heroicons outline file (without .svg). Keep alphabetical. */
export const ICONS = {
  'academic-cap': 'academic-cap',
  adjustments: 'adjustments-horizontal',
  'arrow-down': 'arrow-down',
  'arrow-left': 'arrow-left',
  'arrow-right': 'arrow-right',
  'arrow-up': 'arrow-up',
  bolt: 'bolt',
  'book-open': 'book-open',
  building: 'building-office-2',
  calendar: 'calendar-days',
  'chart-bar': 'chart-bar',
  chat: 'chat-bubble-left-right',
  check: 'check',
  'check-circle': 'check-circle',
  'chevron-down': 'chevron-down',
  'chevron-left': 'chevron-left',
  'chevron-right': 'chevron-right',
  'chevron-up': 'chevron-up',
  clock: 'clock',
  close: 'x-mark',
  cloud: 'cloud',
  code: 'code-bracket',
  copy: 'clipboard-document',
  cpu: 'cpu-chip',
  'credit-card': 'credit-card',
  database: 'circle-stack',
  document: 'document-text',
  download: 'arrow-down-tray',
  edit: 'pencil-square',
  expand: 'arrows-pointing-out',
  'external-link': 'arrow-top-right-on-square',
  eye: 'eye',
  'eye-off': 'eye-slash',
  filter: 'funnel',
  flag: 'flag',
  globe: 'globe-alt',
  grid: 'squares-2x2',
  home: 'home',
  image: 'photo',
  info: 'information-circle',
  language: 'language',
  layers: 'square-3-stack-3d',
  link: 'link',
  list: 'list-bullet',
  'location-pin': 'map-pin',
  lock: 'lock-closed',
  mail: 'envelope',
  menu: 'bars-3',
  microphone: 'microphone',
  minus: 'minus',
  plus: 'plus',
  presentation: 'presentation-chart-bar',
  rocket: 'rocket-launch',
  rss: 'rss',
  search: 'magnifying-glass',
  server: 'server-stack',
  share: 'share',
  shield: 'shield-exclamation',
  'shield-check': 'shield-check',
  sparkles: 'sparkles',
  star: 'star',
  tag: 'tag',
  terminal: 'command-line',
  'trending-down': 'arrow-trending-down',
  'trending-up': 'arrow-trending-up',
  user: 'user',
  users: 'user-group',
  wand: 'cursor-arrow-rays',
  warning: 'exclamation-triangle',
  wrench: 'wrench-screwdriver',
  'zoom-in': 'magnifying-glass-plus',
};

function innerSvg(file) {
  const svg = readFileSync(join(HERO, `${file}.svg`), 'utf8');
  const inner = svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .trim();
  return inner.replace(/\s+/g, ' ').replace(/> </g, '><');
}

const names = Object.keys(ICONS).sort();
const out = [];
out.push('{%- comment -%}');
out.push('GENERATED by scripts/build_icons.mjs from Heroicons (MIT) — do not hand-edit.');
out.push('Usage: {% include icon.html name="shield" size="xs|sm|md|lg|xl" class="text-brand-warn" %}');
out.push('Renders an inline, aria-hidden SVG. Always pair with visible or sr-only text.');
out.push(`Names: ${names.join(' ')}`);
out.push('{%- endcomment -%}');
out.push("{%- assign icon_name = include.name | default: 'info' -%}");
out.push("{%- assign icon_size = include.size | default: 'md' -%}");
out.push(
  "{%- case icon_size -%}{%- when 'xs' -%}{%- assign icon_size_class = 'h-3 w-3' -%}{%- when 'sm' -%}{%- assign icon_size_class = 'h-4 w-4' -%}{%- when 'lg' -%}{%- assign icon_size_class = 'h-6 w-6' -%}{%- when 'xl' -%}{%- assign icon_size_class = 'h-8 w-8' -%}{%- else -%}{%- assign icon_size_class = 'h-5 w-5' -%}{%- endcase -%}"
);
out.push(
  '<svg class="shrink-0 {{ icon_size_class }} {{ include.class }}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true" focusable="false">'
);
out.push('{%- case icon_name -%}');
for (const name of names) {
  out.push(`{%- when '${name}' -%}${innerSvg(ICONS[name])}`);
}
out.push(
  '{%- else -%}<circle cx="12" cy="12" r="9"/><path stroke-linecap="round" d="M12 8h.01M11 12h1v4h1"/>'
);
out.push('{%- endcase -%}');
out.push('</svg>');
writeFileSync(join(root, '_includes', 'icon.html'), out.join('\n') + '\n');
console.log(
  `icon.html: ${names.length} icons — review the diff and update quality/vendored-assets.json before committing`
);
